[package]
name = "rosetta-stone-quickbasic"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
description = "QuickBASIC / QBASIC frontend for Rosetta transpiler"

[dependencies]
rosetta-stone-core = { workspace = true }
rosetta-stone-ir = { workspace = true }
thiserror = { workspace = true }
